//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class 应收款
    {
        public int ID { get; set; }
        public string 概要编号 { get; set; }
        public Nullable<int> 概要项ID { get; set; }
        public Nullable<int> 房产单元ID { get; set; }
        public Nullable<int> 费用项目ID { get; set; }
        public string 资源表名称 { get; set; }
        public Nullable<int> 资源表ID { get; set; }
        public string 资源表编号 { get; set; }
        public Nullable<int> 占用者ID { get; set; }
        public string 占用者身份 { get; set; }
        public string 计费年月 { get; set; }
        public Nullable<System.DateTime> 计费年月开始日期 { get; set; }
        public Nullable<System.DateTime> 计费年月截至日期 { get; set; }
        public Nullable<System.DateTime> 应收日期 { get; set; }
        public Nullable<short> 应收延期 { get; set; }
        public Nullable<int> 费用计算公式ID { get; set; }
        public Nullable<decimal> 应收金额 { get; set; }
        public Nullable<int> 滞纳金公式ID { get; set; }
        public Nullable<System.DateTime> 滞纳金计算日期 { get; set; }
        public Nullable<short> 滞纳金计算延期 { get; set; }
        public Nullable<decimal> 滞纳金金额 { get; set; }
        public Nullable<decimal> 优惠金额 { get; set; }
        public string 缓交年月 { get; set; }
        public string 费用说明 { get; set; }
        public string 收费状态 { get; set; }
        public Nullable<int> 收款ID { get; set; }
        public Nullable<int> 收据ID { get; set; }
        public Nullable<int> 划帐文件ID { get; set; }
        public Nullable<int> 占用表ID { get; set; }
        public Nullable<bool> 尾数标记 { get; set; }
        public Nullable<int> 变更表ID { get; set; }
        public Nullable<int> 产生来源 { get; set; }
        public Nullable<System.DateTime> 监控日期 { get; set; }
        public Nullable<System.DateTime> 计算滞纳金日期 { get; set; }
        public Nullable<int> 扣减标识 { get; set; }
        public Nullable<decimal> 应收调整金额 { get; set; }
        public string 币种代码 { get; set; }
        public Nullable<decimal> 汇率 { get; set; }
        public string 帐套代码 { get; set; }
        public Nullable<int> 另存源ID { get; set; }
    }
}
